name=ESP32 MQTTv5
version=1.0.0
author=Jorge Gaspar Beltre Rivera
maintainer=Jorge Gaspar Beltre Rivera
sentence=MQTT 5.0 client library for ESP32
paragraph=Full MQTT 5.0 implementation with properties, reason codes, and simple API
category=Communication
url=https://github.com/JorgeGBeltre/ESP32_MQTTv5
architectures=esp32,esp32s2,esp32s3,esp32c3,esp32c6
depends=ArduinoJson
includes=ESP32_MQTTv5.h
dot_a_linkage=false